import { loadCurrentAccount, setupAuth } from "./js/auth.js";
import { setupAudioProfiles } from "./js/audio-profiles.js";
import { setupFinishedCallPanelCleanup } from "./js/call-finished-panel.js";
import { setupCalls } from "./js/calls.js";
import { checkServer, setupHealth } from "./js/health.js";
import { setupInvites } from "./js/invites.js";
import { setupMessageAnnouncements } from "./js/message-announcements.js";
import { setupMessageScroll } from "./js/message-scroll.js";
import { setupMessenger } from "./js/messenger.js";
import { setupPushNotifications } from "./js/push.js";
import { setupSessions } from "./js/sessions.js";
import { setupAppleVoiceRecordingPreference } from "./js/voice-apple-recording.js";
import { setupVoicePlayer } from "./js/voice-player.js";
import { setupVoiceRecorder } from "./js/voice-recorder.js";
import { setupVoiceSettings } from "./js/voice-settings.js";
import { setupVoiceWebKitTimelineFix } from "./js/voice-webkit-timeline.js";

setupHealth();
setupAuth();
setupSessions();
setupInvites();
setupMessenger();
setupMessageAnnouncements();
setupMessageScroll();
setupPushNotifications();
setupVoiceSettings();
setupVoicePlayer();
setupVoiceWebKitTimelineFix();
setupAppleVoiceRecordingPreference();
setupFinishedCallPanelCleanup();
setupVoiceRecorder();
setupAudioProfiles();
setupCalls();

await checkServer();
await loadCurrentAccount({ quiet: false });
